language: node_js
node_js:
  - "9"
install:
  - cd ..
  - mkdir hyoo
  - mv notes.hyoo.ru hyoo/notes
  - git init
  - git remote add origin https://github.com/eigenmethod/mam.git
  - git pull origin master
  - npm install
script:
  - npm start hyoo/notes
  - rm hyoo/notes/.gitignore
  - mv hyoo/notes/- notes.hyoo.ru
  - mv hyoo/notes/CNAME notes.hyoo.ru/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: .
  on:
    branch: master
